# Generated by Django 4.0.4 on 2022-05-17 05:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='otp_veriied',
        ),
        migrations.AddField(
            model_name='account',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.BigIntegerField()),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('landmark', models.CharField(max_length=50)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.account')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
