# Generated by Django 4.0.4 on 2022-05-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_account_otp_veriied_account_otp_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='otp_verified',
        ),
    ]
