# Generated by Django 4.0.4 on 2022-05-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_account_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
