# Generated by Django 4.0.4 on 2022-06-13 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_category_options_category_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Myorder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
