# Generated by Django 4.0.4 on 2022-06-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_status_myorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
